### ISSUE TITLE
Does not work as part of a repeater field

### ISSUE THREAD

**Issue by Alpine418** [Toutouwai/CkeLinkFiles#2]
When the ckeditor is part of a repeater field, the file selector does not recognize the uploaded files which are also part of a repeater field.

foo = repeater field
foo.body_copy = textarea field with ckeditor
foo.fields =files field

**Comment by Toutouwai** [comment]
This isn't a bug - the module readme says: 

> Adds a menu to CKEditor to allow the quick insertion of links to files _on the page being edited_.

That means the page that is open in Page Edit and not any Repeater page.

But I'll consider this as a feature request and see if it can be accommodated.

**Comment by Toutouwai** [comment]
I added support for this in v0.1.6: https://processwire.com/talk/topic/18205-ckeditor-link-files/?do=findComment&comment=193326
